#!/bin/bash

#
# SynthStrip SLURM Job Script
# 
# This script runs FreeSurfer's mri_synthstrip for brain extraction
# on a SLURM cluster for a single subject/session.
#
# By default (SEPARATE_MASKS=false), only a reference contrast (configurable via REF_BRAIN_MASK_CONTRAST,
# default: T1w) is processed with mri_synthstrip. For other acquisition types, symbolic links are
# created pointing to the reference mask, and brain-extracted images are generated by applying
# the reference mask. This ensures consistent brain masks across all contrasts while saving computation time.
# Files are matched across acquisition types using stable BIDS entities (subject, session, run, echo, part),
# ignoring acquisition-specific entities like MT-on/MT-off or flip angles.
#
# Usage: sbatch synthstrip_slurm.sh <INPUT_DIR> <OUTPUT_DIR> <SUBJECT> [SESSION] <ACQ_TYPES> [NO_CSF] [HOLEFILL] [HOLEFILL_ITERATIONS] [SEPARATE_MASKS]
#
# Arguments:
#   INPUT_DIR           - Path to input BIDS directory containing raw data
#   OUTPUT_DIR          - Path to output directory for processed results
#   SUBJECT             - Subject identifier (e.g., sub-001)
#   SESSION             - (Optional) Session identifier (e.g., ses-01) (pass empty string if none)
#   ACQ_TYPES           - Comma-separated list of acquisition types (e.g., PDw,T1w,MTw)
#   NO_CSF              - (Optional) Set to 'true' to exclude CSF from brain mask
#   HOLEFILL            - (Optional) Set to 'true' to enable mask hole-filling
#   HOLEFILL_ITERATIONS - (Optional) Number of dilation/erosion iterations for hole-filling
#   SEPARATE_MASKS      - (Optional) Set to 'true' to create separate brain masks for each acquisition type
#                         (default: false - use shared reference contrast mask with symlinks)
#
# The script processes anatomical data using mri_synthstrip with the following features:
#   - Brain extraction for reference or all acquisition types (depending on SEPARATE_MASKS)
#   - GPU acceleration (if available)
#   - Generates both brain-extracted images (_brain.nii) and masks (_mask.nii)
#   - Mask hole-filling with configurable iterations (optional)
#
# Output is placed in OUTPUT_DIR maintaining BIDS structure.
#

#SBATCH -c 8
#SBATCH --mem 32G
#SBATCH --time 60
#SBATCH -o /data/u_kuegler_software/git/qsm/run_qsmxt/logs/%j_synthstrip.out

# Software versions
FREESURFER_VERSION="7.4.1"
FSL_VERSION="6.0.6"

INPUT_DIR="$1"
OUTPUT_DIR="$2"
SUBJECT="$3"
SESSION="$4"
ACQ_TYPES="$5"
NO_CSF="${6:-false}"
HOLEFILL="${7:-false}"
HOLEFILL_ITERATIONS="$8"
SEPARATE_MASKS="${9:-false}"

echo "Input Directory: ${INPUT_DIR}"
echo "Output Directory: ${OUTPUT_DIR}"
echo "Subject: ${SUBJECT}"
if [[ -n "$SESSION" ]]; then
    echo "Session: ${SESSION}"
else
    echo "Session: Not specified (processing subject without session directory)"
fi
echo "Acquisition Types: ${ACQ_TYPES}"
echo "Exclude CSF: ${NO_CSF}"
echo "Hole-filling: ${HOLEFILL}"
if [ "$HOLEFILL" = "true" ]; then
    echo "Hole-filling iterations: ${HOLEFILL_ITERATIONS}"
fi
echo "Separate brain masks: ${SEPARATE_MASKS}"
echo "--------"

# Contrast used for brain mask creation (only relevant if SEPARATE_MASKS=false)
# This contrast will be stripped and used as reference mask for all other contrasts
REF_BRAIN_MASK_CONTRAST="T1w"

# Input file pattern for matching magnitude images (acq, echo-1, part-mag)
# is specified directly in the loops for pass 1 and 2 (see below)

# Function to create a matching key from stable BIDS entities
# This key is used to match files across different acquisition types
# Arguments: base filename (without extension)
# Returns: key string based on stable entities (sub, ses, run, echo, part)
create_matching_key() {
    local base="$1"
    # Extract prefix (everything before _acq-)
    local prefix="${base%%_acq-*}"
    # Extract echo number
    local echo_num=$(echo "$base" | grep -oP '_echo-\K[0-9]+' || echo "")
    # Extract part (mag/phase/real/imag)
    local part=$(echo "$base" | grep -oP '_part-\K[a-z]+' || echo "")
    # Return key from stable entities only
    echo "${prefix}_echo-${echo_num}_part-${part}"
}

# Check for GPU availability
GPU_FLAG=""
if command -v nvidia-smi &> /dev/null && nvidia-smi &> /dev/null; then
    echo "GPU detected - using GPU acceleration"
    GPU_FLAG="--gpu"
else
    echo "No GPU detected - using CPU only"
fi

# Set CSF flag
CSF_FLAG=""
if [ "$NO_CSF" = "true" ]; then
    echo "CSF exclusion enabled"
    CSF_FLAG="--no-csf"
fi

# Construct paths - handle optional session
if [[ -n "$SESSION" ]]; then
    INPUT_ANAT_DIR="${INPUT_DIR}/${SUBJECT}/${SESSION}/anat"
    OUTPUT_ANAT_DIR="${OUTPUT_DIR}/${SUBJECT}/${SESSION}/anat"
    PROCESSING_MSG="${SUBJECT}/${SESSION}"
else
    INPUT_ANAT_DIR="${INPUT_DIR}/${SUBJECT}/anat"
    OUTPUT_ANAT_DIR="${OUTPUT_DIR}/${SUBJECT}/anat"
    PROCESSING_MSG="${SUBJECT}"
fi

# Create output directory
mkdir -p "${OUTPUT_ANAT_DIR}"

echo "Processing brain extraction for ${PROCESSING_MSG}..."

# Determine which acquisition types to actually process with synthstrip
if [ "$SEPARATE_MASKS" = "true" ]; then
    # process all acquisition types
    PROCESS_ACQ_TYPES="$ACQ_TYPES"
    echo "Separate brain masks mode: Processing brain mask for all acquisition types"
else
    # default behavior: only process reference contrast for brain mask
    PROCESS_ACQ_TYPES="$REF_BRAIN_MASK_CONTRAST"
    echo "Shared brain mask mode: Processing only ${REF_BRAIN_MASK_CONTRAST}, will create symlinks for other acquisition types"
fi

echo "--------"

# Convert comma-separated acquisition types to array
IFS=',' read -ra PROCESS_ACQ_ARRAY <<< "$PROCESS_ACQ_TYPES"
IFS=',' read -ra ALL_ACQ_ARRAY <<< "$ACQ_TYPES"

# Check if reference contrast is available in ACQ_TYPES when using shared mask mode
if [ "$SEPARATE_MASKS" = "false" ]; then
    contrast_found=false
    for acq in "${ALL_ACQ_ARRAY[@]}"; do
        if [ "$acq" = "$REF_BRAIN_MASK_CONTRAST" ]; then
            contrast_found=true
            break
        fi
    done
    
    if [ "$contrast_found" = "false" ]; then
        echo "Error: Reference contrast '${REF_BRAIN_MASK_CONTRAST}' not found in acquisition types list: ${ACQ_TYPES}"
        echo "Cannot create shared brain mask without reference contrast."
        echo "Either add '${REF_BRAIN_MASK_CONTRAST}' to ACQ_TYPES or use --separate-masks flag."
        exit 1
    fi
fi

# Declare associative arrays to store reference contrast mask and brain paths for later symlinking
# Key will be the filename with acquisition type removed
declare -A REF_CONTRAST_MASK_PATHS
declare -A REF_CONTRAST_BRAIN_PATHS

# First pass: Process acquisition types with synthstrip (reference contrast only by default, or all if SEPARATE_MASKS=true)
for acq in "${PROCESS_ACQ_ARRAY[@]}"; do
    echo "  Processing acquisition type: ${acq}"
    
    # First pass: count matching files
    matching_files=()
    for input_file in "${INPUT_ANAT_DIR}"/*_acq-${acq}*_echo-{01,1}_*_part-mag*.nii*; do
        if [ -f "$input_file" ]; then
            matching_files+=("$input_file")
        fi
    done
    
    # Warn if multiple files found
    if [ ${#matching_files[@]} -gt 1 ]; then
        echo "    Warning: Found ${#matching_files[@]} files for acquisition type ${acq} - processing all"
    fi
    
    # Process each matching file
    files_processed=0
    for input_file in "${matching_files[@]}"; do
        if [ -f "$input_file" ]; then
            files_processed=$((files_processed + 1))
            
            # Get the base filename without extension
            basename_file=$(basename "$input_file")
            # Remove .nii.gz or .nii extension
            if [[ "$basename_file" == *.nii.gz ]]; then
                base="${basename_file%.nii.gz}"
                ext=".nii.gz"
            else
                base="${basename_file%.nii}"
                ext=".nii"
            fi
            
            # Construct output filenames
            output_brain="${OUTPUT_ANAT_DIR}/${base}_brain${ext}"
            output_mask="${OUTPUT_ANAT_DIR}/${base}_mask${ext}"
            
            echo "    Processing: $basename_file"
            
            # Run mri_synthstrip
            SCWRAP freesurfer ${FREESURFER_VERSION} \
            mri_synthstrip \
                -i "$input_file" \
                -o "$output_brain" \
                -m "$output_mask" \
                $GPU_FLAG \
                $CSF_FLAG
            
            if [ $? -eq 0 ]; then
                echo "    Success: Created brain and mask files"
                
                # If processing reference contrast, store the paths for later use in symlink creation
                if [ "$acq" = "$REF_BRAIN_MASK_CONTRAST" ]; then
                    # Create a robust key from stable BIDS entities (sub, ses, run, echo, part)
                    key=$(create_matching_key "$base")
                    REF_CONTRAST_MASK_PATHS["$key"]="$output_mask"
                    REF_CONTRAST_BRAIN_PATHS["$key"]="$output_brain"
                    echo "    Stored ${REF_BRAIN_MASK_CONTRAST} mask path for key: $key"
                fi
                
                echo "    --------"
                
                # Run hole-filling if requested
                if [ "$HOLEFILL" = "true" ]; then
                    echo "Performing hole-filling with ${HOLEFILL_ITERATIONS} dilation/erosion iterations..."
                    
                    # Build the fslmaths command with specified iterations
                    cmd="SCWRAP fsl ${FSL_VERSION} fslmaths \"$output_mask\" -kernel sphere 1"
                    
                    # Add dilation operations
                    for ((i=1; i<=HOLEFILL_ITERATIONS; i++)); do
                        cmd="$cmd -dilM"
                    done
                    
                    # Add erosion operations
                    for ((i=1; i<=HOLEFILL_ITERATIONS; i++)); do
                        cmd="$cmd -ero"
                    done
                    
                    # Overwrite the original mask
                    cmd="$cmd \"$output_mask\""
                    
                    # Execute the hole-filling command
                    eval $cmd
                    
                    if [ $? -eq 0 ]; then
                        echo "    Success: Created filled mask"
                        
                        # Decompress mask if FSL created .nii.gz
                        if [ -f "${output_mask}.gz" ]; then
                            echo "Decompressing mask..."
                            gunzip -f "${output_mask}.gz"
                        fi
                        
                        # Apply the filled mask to the input file to create new brain image
                        echo "Applying filled mask to input image..."
                        SCWRAP fsl ${FSL_VERSION} fslmaths "$input_file" -mas "$output_mask" "$output_brain"
                        
                        if [ $? -eq 0 ]; then
                            echo "    Success: Created new brain image using filled mask"
                            
                            # Decompress brain if FSL created .nii.gz
                            if [ -f "${output_brain}.gz" ]; then
                                echo "Decompressing brain..."
                                gunzip -f "${output_brain}.gz"
                            fi
                        else
                            echo "    Error: Failed to apply filled mask to input image"
                        fi
                    else
                        echo "    Error: Failed to perform hole-filling"
                    fi
                fi
            else
                echo "    Error: Failed to process $basename_file"
            fi
        fi
    done
    
    if [ $files_processed -eq 0 ]; then
        echo "    Warning: No files processed for acquisition type ${acq}"
    else
        echo "    Processed $files_processed file(s) for acquisition type ${acq}"
    fi
    echo "--------"
done

# Second pass: Create symlinks for non-reference acquisition types if SEPARATE_MASKS is false
if [ "$SEPARATE_MASKS" = "false" ]; then
    echo "Creating symbolic links for non-${REF_BRAIN_MASK_CONTRAST} acquisition types..."
    
    for acq in "${ALL_ACQ_ARRAY[@]}"; do
        # Skip reference contrast as it was already processed
        if [ "$acq" = "$REF_BRAIN_MASK_CONTRAST" ]; then
            continue
        fi
        
        echo "  Creating symlinks for acquisition type: ${acq}"
        
        # Find matching files for this acquisition type
        matching_files=()
        for input_file in "${INPUT_ANAT_DIR}"/*_acq-${acq}*_echo-{01,1}_*_part-mag*.nii*; do
            if [ -f "$input_file" ]; then
                matching_files+=("$input_file")
            fi
        done
        
        files_processed=0
        for input_file in "${matching_files[@]}"; do
            if [ -f "$input_file" ]; then
                files_processed=$((files_processed + 1))
                
                # Get the base filename without extension
                basename_file=$(basename "$input_file")
                if [[ "$basename_file" == *.nii.gz ]]; then
                    base="${basename_file%.nii.gz}"
                    ext=".nii.gz"
                else
                    base="${basename_file%.nii}"
                    ext=".nii"
                fi
                
                # Construct output filenames
                output_brain="${OUTPUT_ANAT_DIR}/${base}_brain${ext}"
                output_mask="${OUTPUT_ANAT_DIR}/${base}_mask${ext}"
                
                # Create matching key using the same logic as during reference contrast masking
                key=$(create_matching_key "$base")
                
                # Look up the corresponding reference contrast mask
                ref_contrast_mask="${REF_CONTRAST_MASK_PATHS[$key]}"
                
                # Check if reference contrast mask exists
                if [ -z "$ref_contrast_mask" ] || [ ! -f "$ref_contrast_mask" ]; then
                    echo "    Warning: ${REF_BRAIN_MASK_CONTRAST} mask not found for $basename_file (key: $key)"
                    echo "    Skipping symlink creation for this file"
                    continue
                fi
                
                echo "    Creating mask symlink: $(basename "$output_mask") -> $(basename "$ref_contrast_mask")"
                
                # Create relative symlink for mask
                ln -sf "$(basename "$ref_contrast_mask")" "$output_mask"
                
                if [ $? -eq 0 ]; then
                    echo "    Success: Created mask symlink"
                    
                    # Apply the reference contrast mask to the input file to create brain-extracted image
                    echo "    Applying ${REF_BRAIN_MASK_CONTRAST} mask to ${acq} image..."
                    SCWRAP fsl ${FSL_VERSION} fslmaths "$input_file" -mas "$ref_contrast_mask" "$output_brain"
                    
                    if [ $? -eq 0 ]; then
                        echo "    Success: Created brain-extracted image"
                        
                        # Decompress brain if FSL created .nii.gz
                        if [ -f "${output_brain}.gz" ]; then
                            echo "    Decompressing brain..."
                            gunzip -f "${output_brain}.gz"
                        fi
                    else
                        echo "    Error: Failed to apply ${REF_BRAIN_MASK_CONTRAST} mask to $basename_file"
                    fi
                else
                    echo "    Error: Failed to create symlink for mask"
                fi
            fi
        done
        
        if [ $files_processed -eq 0 ]; then
            echo "    Warning: No files found for acquisition type ${acq}"
        else
            echo "    Created symlinks for $files_processed file(s) for acquisition type ${acq}"
        fi
        echo "--------"
    done
fi

echo "--------"
echo "Brain extraction completed for ${PROCESSING_MSG}"
